platform:
  name: "cpu_arm"
  display_name: "ARM CPU"
  description: "ARM架构CPU推理"

inference:
  engine: "cpu_arm"
  model_format: "onnx"
  device_id: 0
  num_threads: 2
  use_fp16: false
  confidence_threshold: 0.5
  nms_threshold: 0.4
  input_size: [640, 640]
  labels: ["person"]

deployment:
  type: "host"
  requirements:
    - "python>=3.8"
    - "onnxruntime>=1.16.0"
  environment:
    OMP_NUM_THREADS: "2"
