# 算法模型配置文件
# 支持多种视觉识别算法模型

models:
  # YOLOv5 目标检测模型
  yolov5:
    name: "YOLOv5 Object Detection"
    type: "object_detection"
    model_path: "/opt/models/yolov5s.om"
    input_size: [640, 640]
    confidence_threshold: 0.5
    nms_threshold: 0.4
    classes: ["person", "car", "truck", "bus", "motorcycle", "bicycle"]
    description: "YOLOv5目标检测模型，适用于通用目标检测场景"
    
  # YOLOv8 目标检测模型
  yolov8:
    name: "YOLOv8 Object Detection"
    type: "object_detection"
    model_path: "/opt/models/yolov8s.om"
    input_size: [640, 640]
    confidence_threshold: 0.6
    nms_threshold: 0.5
    classes: ["person", "car", "truck", "bus", "motorcycle", "bicycle", "dog", "cat"]
    description: "YOLOv8目标检测模型，精度更高，支持更多类别"
    
  # 人脸检测模型
  face_detection:
    name: "Face Detection"
    type: "face_detection"
    model_path: "/opt/models/face_detection.om"
    input_size: [320, 320]
    confidence_threshold: 0.7
    nms_threshold: 0.3
    classes: ["face"]
    description: "专门用于人脸检测的模型"
    
  # 车辆检测模型
  vehicle_detection:
    name: "Vehicle Detection"
    type: "vehicle_detection"
    model_path: "/opt/models/vehicle_detection.om"
    input_size: [512, 512]
    confidence_threshold: 0.6
    nms_threshold: 0.4
    classes: ["car", "truck", "bus", "motorcycle", "bicycle"]
    description: "专门用于车辆检测的模型，适用于交通监控场景"
    
  # 人员检测模型
  person_detection:
    name: "Person Detection"
    type: "person_detection"
    model_path: "/opt/models/person_detection.om"
    input_size: [416, 416]
    confidence_threshold: 0.5
    nms_threshold: 0.3
    classes: ["person"]
    description: "专门用于人员检测的模型，适用于安防监控场景"
    
  # 入侵检测模型
  intrusion_detection:
    name: "Intrusion Detection"
    type: "intrusion_detection"
    model_path: "/opt/models/intrusion_detection.om"
    input_size: [640, 640]
    confidence_threshold: 0.7
    nms_threshold: 0.4
    classes: ["person", "vehicle"]
    description: "入侵检测专用模型，适用于周界安防场景"

# 模型配置预设
model_presets:
  # 高精度模式
  high_accuracy:
    confidence_threshold: 0.8
    nms_threshold: 0.3
    description: "高精度模式，减少误报但可能漏检"
    
  # 平衡模式
  balanced:
    confidence_threshold: 0.6
    nms_threshold: 0.4
    description: "平衡模式，精度和召回率均衡"
    
  # 高召回率模式
  high_recall:
    confidence_threshold: 0.4
    nms_threshold: 0.5
    description: "高召回率模式，减少漏检但可能增加误报"
    
  # 实时模式
  realtime:
    confidence_threshold: 0.5
    nms_threshold: 0.4
    input_size: [416, 416]
    description: "实时模式，优先考虑处理速度"

# 场景配置
scenarios:
  # 安防监控场景
  security_monitoring:
    recommended_models: ["person_detection", "intrusion_detection"]
    preset: "balanced"
    alert_rules:
      - target_class: "person"
        min_confidence: 0.6
        alert_message: "检测到人员活动"
    
  # 交通监控场景
  traffic_monitoring:
    recommended_models: ["vehicle_detection", "yolov8"]
    preset: "balanced"
    alert_rules:
      - target_class: "car"
        min_confidence: 0.6
        alert_message: "检测到车辆"
      - target_class: "truck"
        min_confidence: 0.7
        alert_message: "检测到大型车辆"
    
  # 通用监控场景
  general_monitoring:
    recommended_models: ["yolov5", "yolov8"]
    preset: "balanced"
    alert_rules:
      - target_class: "person"
        min_confidence: 0.5
        alert_message: "检测到目标对象"
    
  # 高精度分析场景
  high_precision_analysis:
    recommended_models: ["yolov8", "face_detection"]
    preset: "high_accuracy"
    alert_rules:
      - target_class: "face"
        min_confidence: 0.8
        alert_message: "检测到人脸" 