# AI Edge Platform Configuration

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "ai_edge"
  password: "ai_edge_password"
  database: "ai_edge"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 300s

# gRPC配置
grpc:
  host: "0.0.0.0"
  port: 9090
  inference_service_addr: "localhost:9091"  # Python推理服务地址
  max_recv_msg_size: 10485760  # 10MB
  max_send_msg_size: 10485760  # 10MB
  keepalive_time: 10s
  keepalive_timeout: 1s
  keepalive_enforcement_min_time: 5s
  max_connection_idle: 15s
  max_connection_age: 30s
  max_connection_age_grace: 5s

# JWT配置
jwt:
  secret: "your-secret-key-change-this-in-production"
  expires_in: 24h
  refresh_expires_in: 168h  # 7 days
  issuer: "ai-edge-platform"

# 日志配置
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file
  file_path: "logs/app.log"
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true

# 文件存储配置
storage:
  type: "local"  # local, s3, oss
  local:
    upload_path: "uploads"
    max_file_size: 104857600  # 100MB
    allowed_extensions: [".jpg", ".jpeg", ".png", ".mp4", ".avi", ".mov"]
  s3:
    region: "us-west-2"
    bucket: "ai-edge-storage"
    access_key: ""
    secret_key: ""
    endpoint: ""

# 推理配置
inference:
  timeout: 30s
  max_batch_size: 10
  retry_count: 3
  retry_delay: 1s
  model_cache_size: 5
  default_confidence_threshold: 0.5

# 任务调度配置
scheduler:
  enabled: true
  check_interval: 10s
  max_concurrent_tasks: 10
  task_timeout: 300s

# 监控配置
monitoring:
  enabled: true
  health_check_path: "/health"
  pprof_enabled: false
  pprof_path: "/debug/pprof"

# 告警配置
alerting:
  enabled: true
  channels:
    email:
      enabled: false
      smtp_host: "smtp.gmail.com"
      smtp_port: 587
      username: ""
      password: ""
      from: "noreply@ai-edge.com"
    webhook:
      enabled: false
      url: ""
      timeout: 10s
    slack:
      enabled: false
      webhook_url: ""
      channel: "#alerts"

# 安全配置
security:
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    exposed_headers: ["Content-Length"]
    allow_credentials: true
    max_age: 86400
  rate_limit:
    enabled: true
    requests_per_minute: 100
    burst: 10
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# 开发配置
development:
  auto_migrate: true
  seed_data: false
  debug_sql: false
  mock_inference: true